ANDROID: rfkill: fix unused function warning
As reported by kernelci, a number of kernel configurations fail to build

ERROR: "rfkill_resume_polling" [net/wireless/cfg80211.ko] undefined!

This marks the functions as __maybe_unused to remove the #ifdef, and uses
a conditional reference to the pm operations instead, which will work
in any combination.

A similar patch is needed for android-4.4 and 4.9, this one is for 3.18.

Link: https://kernelci.org/build/id/591063b959b514cac1b12d51/logs/
Fixes: 1fb6edeb817a ("ANDROID: rfkill: Introduce CONFIG_RFKILL_PM and use instead of CONFIG_PM to power down")
Cc: Nick Pelly <npelly@google.com>
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@google.com>